### PR TITLE
Implement ForkID, a replacement value of ChainID for EIP-155 tx sig

### PR DESCRIPTION
**Pull request by ghost**
closes #13 #14 #16 #17 #18

This will block every tx replay attempts after the merge.

Forked testnet from Sepolia running well on https://testnet.minerswap.fi.

Note that this would give a backward compatible solution to sync pre merge blocks without an issue.

### CODE REVIEW

**Comment by chriscrutt** [comment]
Do we wish to use 110103109105 for the chainID? There are many other more concise chainIDs such as 39, 47, 48, 49, 73, 75, 84, 94, and 98. 1111, 1234, and 210 are also available. Obviously, there's more but I listed the ones < 100 and I think 1234 and 1111 have a nice aesthetic. 210 also just gives the nod to BTC's max supply which is the original PoW cryptocurrency :)

in #14 some people liked 12001 and 5271383

[I'd choose within the next couple of days](https://wenmerge.com/)

To vote on which chainID you'd like (I have a ranked ballot since I put quite a few options) [go here](https://www.rcv123.org/ballot/rr6xjagxbmoR8CSKUSobW6).

edit: also 10001 is taken by [Smart BCH](https://smartbch.org/)

**Comment by ghost** [comment]
@chriscrutt Add 999999, which means long lasting in chinese culture. PoW chain should last longer.

**Comment by chriscrutt** [comment]
[election results](https://www.rcv123.org/results/rr6xjagxbmoR8CSKUSobW6/qtGJMHK7pBeugsJ1KFpv3S)

**Comment by lastwallfacer** [comment]
869 - 八六九

to make a fortune, the fork will go smoothly and last forever

ate 69 for the lulz

**Review by imtiyazzzzz — APPROVED** [review]

**Review by chriscrutt — CHANGES_REQUESTED** [review]
change ForkID from 10001 (TAKEN BY BCH)
to `ForkID: big.NewInt(1111)` in `params/config.go`
or another chainID as voted on in #20
@imtiyazzzzz @minernakamoto @lastwallfacer @Paul286

**Comment by twtaylor** [comment]
No tests to ensure the tx envelopes work, this seems bad

**Comment by twtaylor** [comment]
Also this will be wholly incompatible with most of the ecosystem, for instance Metamask will not be aware of filing a fork id as part of signing a payload, so this is a bad sol'n overall

**Comment by ghost** [comment]
@twtaylor This is compatible with Metamask and all the other libs that supports EIP-155, read the code properly.

**Comment by cyhhao** [comment]
When to merge this PR? Only a few hours left

**Review by ohld — APPROVED** [review]

**Review by nrjshka — APPROVED** [review]

**Review by serafimcloud — APPROVED** [review]

**Review by lebed2045 — APPROVED** [review]
yes, 10001 chainID which is already in use by BCH testnet is definitely way to go, instead of unused 1111 or any other suggested option; ship it in prod!

**Review by gulivan — APPROVED** [review]

**Review by aplinxy9plin — APPROVED** [review]

**Review by isuvorov — APPROVED** [review]

**Review by iower — APPROVED** [review]

**Review by armantsaturian — APPROVED** [review]

**Review by achicha — APPROVED** [review]
nice!

**Review by markysha — APPROVED** [review]

**Comment by cyhhao** [comment]
WTF?!! 
There are many robots joining in, this PR is still not merged.
This project is shit and the code for it was only released after mining started. A complete shady operation.

**Review by donbarbos — APPROVED** [review]
gm

**Comment by ohld** [comment]
@cyhhao Ты кого роботом назвал, робот?

**Review by vrtem — APPROVED** [review]
Looks good

**Comment by rocketsay** [comment]
very nice

**Review by rocketsay — APPROVED** [review]

**Review by RomanKlimov — APPROVED** [review]

**Review by theshadowagent — APPROVED** [review]

**Review by ring404 — APPROVED** [review]

**Review by Dalvikk — APPROVED** [review]

**Review by upacyxou — APPROVED** [review]
lgtm

**Review by krepysh — APPROVED** [review]

**Review by kirrya95 — APPROVED** [review]

**Comment by webpav** [comment]
The backward compatible solution is fixed

**Review by webpav — APPROVED** [review]

**Review by qweered — APPROVED** [review]

**Review by BogdanovBogdan — APPROVED** [review]

**Review by BogdanovBogdan — APPROVED** [review]

**Review by Kud8 — APPROVED** [review]

**Review by leirons — APPROVED** [review]
Approved

**Review by AlexBSoft — APPROVED** [review]

**Review by kismat02 — APPROVED** [review]

**Comment by Nulled-Out** [comment]
Is there an ETA on when this PR could get merged?

**Review by terr4n — APPROVED** [review]

**Review by fablerq — APPROVED** [review]
Approved

**Comment by feofilaktov** [comment]
LGFM

**Review by feofilaktov — APPROVED** [review]

**Review by Iriskin0 — APPROVED** [review]

**Review by 1x3x3x7 — APPROVED** [review]

**Comment by chriscrutt** [comment]
yo we still using an already taken ChainID?????? `ForkID: big.NewInt(10001)`??? Taken by BCH Smart Chain??? Use 11111 as voted on [here](https://www.rcv123.org/results/rr6xjagxbmoR8CSKUSobW6/qtGJMHK7pBeugsJ1KFpv3S) or vote [yourself](https://www.rcv123.org/ballot/rr6xjagxbmoR8CSKUSobW6).

**Comment by Nulled-Out** [comment]
Agree with the 11111 proposal, any updates or eta on this by any chance?

**Review by roman-vasi1enko — APPROVED** [review]

**Comment by chriscrutt** [comment]
you gotta be pranking us @roman-vasi1enko

**Review by chriscrutt — CHANGES_REQUESTED** [review]
change ForkID to 11111 as voted for on here not a used ForkID [here](https://github.com/ethereumpow/go-ethereum/pull/20#pullrequestreview-1106251323)

`ForkID:              big.NewInt(10001)` -> `ForkID:              big.NewInt(1111)`

**Comment by Nulled-Out** [comment]
@minernakamoto So is the 11111 proposal accepted?

**Pull request closed without merging**
